
export const COLORS = {
  JIRAI_DARK: '#0F1115',
  JIRAI_PANEL: '#181B21',
  JIRAI_BORDER: '#2D313A',
  JIRAI_ACCENT: '#FF4F5E',
  JIRAI_ACCENT_GLOW: 'rgba(255, 79, 94, 0.3)',
  JIRAI_SECONDARY: '#4A9EFF',
  TEXT_MAIN: '#E0E0E0',
  TEXT_MUTED: '#888888',
  SUCCESS: '#10B981',
  WARNING: '#F59E0B',
  INFO: '#4A9EFF',
  ERROR: '#EF4444',
  PURPLE: '#8B5CF6',
  RED: '#EF4444',
  OVERLAY_BG: 'rgba(0, 0, 0, 0.4)',
} as const;

export const SIZES = {
  NODE_MIN_WIDTH: 160,
  NODE_MIN_HEIGHT: 96,
  NODE_MAX_WIDTH: 500,
  TIMELINE_COL_WIDTH: 320,
  TIMELINE_HEADER_HEIGHT: 128,
  CALENDAR_CELL_WIDTH: 250,
  CALENDAR_CELL_HEIGHT: 200,
  MOBILE_HEADER_HEIGHT: 80,
  DESKTOP_HEADER_HEIGHT: 128,
  TOUCH_TARGET: 44,
} as const;

export const Z_INDEX = {
  CANVAS: 0,
  HEADER: 10,
  SIDEBAR: 20,
  OVERLAY: 30,
  ASSISTANT: 50,
  PANEL: 60,
  MODAL: 100,
  TOOLTIP: 999,
} as const;

export const LIMITS = {
  MAX_HISTORY: 50,
  MAX_NODES_CONTEXT: 100,
  THINKING_BUDGET: 1024,
  MAX_ZOOM: 5,
  MIN_ZOOM: 0.1,
} as const;

export const STORAGE_KEYS = {
  PERSISTENCE: 'jirai-persistence-v1',
  TUTORIAL_COMPLETED: 'jirai_tutorial_completed',
} as const;

export const MODELS = {
  ANALYSIS: 'gemini-2.5-flash',
} as const;
